[env:ESP32_DIY_2W_LoRa_RJ45]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    ${common.build_flags}
    -D LORAHAM_V2
    -D BOARD_MAX_POWER=22
    -D HAS_W5500                ; Tells the firmware to use W5500 SPI driver
    -I variants/ESP32_DIY_2W_LoRa_RJ45
lib_deps =
    ${common.lib_deps}
    ${common.display_libs}
    arduino-libraries/Ethernet @ ^2.0.2
