[env:ESP32_DIY_2W_LoRa]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    ${common.build_flags}
    -D LORAHAM_V2             ; Use the logic of the working variant
    -D BOARD_MAX_POWER=22     ; Prepare for 2W
    -I variants/ESP32_DIY_2W_LoRa
lib_deps =
    ${common.lib_deps}
    ${common.display_libs}
    ; Add any missing libs we found earlier if they aren't in common
    ayushsharma82/ElegantOTA @ ^3.1.0